spring:
  application:
    name: Secondhand-Library
  datasource:
    url: jdbc:postgresql://localhost:5432/secondhand
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      platform: postgres

  web:
    resources:
      static-locations: classpath:/static/

aladdin:
  api:
    key: "ttbjjsh02081144001"

library:
  api:
    key: "6cbf9798e0f9b2cb2d094901a7bc844cbf54e716d641ccab354f57e694dc8b91"

#jwt
jwt:
  secret:
    key: greenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonT

#kakao
kakao:
  auth:
    client_id: bc9537699d03799a297967214e3bbd2e
    redirect_uri: http://localhost:8080/login/auth
